// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5jLft_500S0tMeTTPPlpD1C1rt5tZhv8',
    appId: '1:412370258086:web:078696d7d44761271ecc67',
    messagingSenderId: '412370258086',
    projectId: 'registrationapp-c2dcf',
    authDomain: 'registrationapp-c2dcf.firebaseapp.com',
    storageBucket: 'registrationapp-c2dcf.firebasestorage.app',
    measurementId: 'G-GY6KPEXNGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNitZOLkCECoh9_q4Emxelm5sVT2_5MZc',
    appId: '1:412370258086:android:fff95eb5164d0d6b1ecc67',
    messagingSenderId: '412370258086',
    projectId: 'registrationapp-c2dcf',
    storageBucket: 'registrationapp-c2dcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0HdABr6w0GRWQWYtl2P6Otz9pJb96RNE',
    appId: '1:412370258086:ios:a47315e389b139e61ecc67',
    messagingSenderId: '412370258086',
    projectId: 'registrationapp-c2dcf',
    storageBucket: 'registrationapp-c2dcf.firebasestorage.app',
    iosBundleId: 'com.example.registrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0HdABr6w0GRWQWYtl2P6Otz9pJb96RNE',
    appId: '1:412370258086:ios:a47315e389b139e61ecc67',
    messagingSenderId: '412370258086',
    projectId: 'registrationapp-c2dcf',
    storageBucket: 'registrationapp-c2dcf.firebasestorage.app',
    iosBundleId: 'com.example.registrationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5jLft_500S0tMeTTPPlpD1C1rt5tZhv8',
    appId: '1:412370258086:web:781fbac2cf23d3f61ecc67',
    messagingSenderId: '412370258086',
    projectId: 'registrationapp-c2dcf',
    authDomain: 'registrationapp-c2dcf.firebaseapp.com',
    storageBucket: 'registrationapp-c2dcf.firebasestorage.app',
    measurementId: 'G-7WLP6NDHSY',
  );
}
